# Generated by Django 4.2.27 on 2026-01-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('gif', 'GIF'), ('mp4', 'MP4'), ('image', 'Image'), ('checkpoint', 'Checkpoint'), ('csv', 'CSV')], max_length=20)),
                ('path', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiments.run')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestep', models.IntegerField()),
                ('is_best', models.BooleanField(default=False)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Artifacts.artifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiments.run')),
            ],
        ),
    ]
