# Generated by Django 4.2.27 on 2026-01-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunMetricsTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_idx', models.IntegerField()),
                ('global_timestep', models.IntegerField()),
                ('mean_reward', models.FloatField()),
                ('std_reward', models.FloatField()),
                ('mean_dx', models.FloatField()),
                ('mean_speed', models.FloatField()),
                ('entropy', models.FloatField(null=True)),
                ('policy_loss', models.FloatField(null=True)),
                ('value_loss', models.FloatField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiments.run')),
            ],
            options={
                'ordering': ['update_idx'],
            },
        ),
        migrations.CreateModel(
            name='RunMetricsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_mean_reward', models.FloatField()),
                ('max_mean_reward', models.FloatField()),
                ('mean_dx_final', models.FloatField()),
                ('smoothness_score', models.FloatField(null=True)),
                ('stability_score', models.FloatField(null=True)),
                ('energy_proxy', models.FloatField(null=True)),
                ('convergence_update', models.IntegerField(null=True)),
                ('plateau_detected', models.BooleanField(default=False)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Experiments.run')),
            ],
        ),
        migrations.CreateModel(
            name='DiversityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iou_score', models.FloatField()),
                ('ncd_score', models.FloatField()),
                ('novelty_score', models.FloatField(null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('reference_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Experiments.run')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversity', to='Experiments.run')),
            ],
        ),
    ]
