# Generated by Django 4.2.27 on 2026-02-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Experiments', '0005_curriculum_visualiseenvs_curriculum'),
        ('Metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diversitymetric',
            name='reference_run',
        ),
        migrations.AlterField(
            model_name='diversitymetric',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversity', to='Experiments.visualiseenvs'),
        ),
        migrations.AlterField(
            model_name='runmetricssummary',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Experiments.timestampenvgenerated'),
        ),
        migrations.AlterField(
            model_name='runmetricstimeseries',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiments.timestampenvgenerated'),
        ),
    ]
