# Generated by Django 4.2.27 on 2026-02-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0003_generatedenv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedEnv',
        ),
    ]
