# Generated by Django 4.2.27 on 2026-04-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Experiments', '0008_generatedenv'),
        ('Metrics', '0004_delete_generatedenv'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentFitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_index', models.IntegerField()),
                ('json_path', models.CharField(max_length=500)),
                ('fitness_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visualise_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiments.visualiseenvs')),
            ],
        ),
        migrations.CreateModel(
            name='RobotPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(max_length=500)),
                ('start_x', models.FloatField()),
                ('max_x', models.FloatField()),
                ('distance_travelled', models.FloatField()),
                ('normalized_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.environmentfitness')),
            ],
        ),
    ]
