# Generated by Django 4.2.27 on 2026-01-24 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid_size_x', models.IntegerField()),
                ('grid_size_y', models.IntegerField()),
                ('voxel_grid', models.TextField()),
                ('env_hash', models.CharField(max_length=64, unique=True)),
                ('difficulty_score', models.FloatField(blank=True, null=True)),
                ('preview_image', models.ImageField(blank=True, upload_to='environments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Morphology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('connections', models.TextField()),
                ('voxel_count', models.IntegerField()),
                ('actuator_count', models.IntegerField()),
                ('morphology_hash', models.CharField(max_length=64, unique=True)),
                ('preview_image', models.ImageField(blank=True, upload_to='morphologies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
